namespace AoC2024.Tests
{
    [TestClass]
    public class Day08Tests
    {
        private const string Input1 = """
                                 ............
                                 ........0...
                                 .....0......
                                 .......0....
                                 ....0.......
                                 ......A.....
                                 ............
                                 ............
                                 ........A...
                                 .........A..
                                 ............
                                 ............
                                 """;

        private const string Input2 = """
                                 ..........
                                 ..........
                                 ..........
                                 ....a.....
                                 ..........
                                 .....a....
                                 ..........
                                 ..........
                                 ..........
                                 ..........
                                 """;
        
        private const string Input3 = """
                                 ..........
                                 ..........
                                 ..........
                                 ....a.....
                                 ........a.
                                 .....a....
                                 ..........
                                 ..........
                                 ..........
                                 ..........
                                 """;

        private const string Input4 = """
                                      T.........
                                      ...T......
                                      .T........
                                      ..........
                                      ..........
                                      ..........
                                      ..........
                                      ..........
                                      ..........
                                      ..........
                                      """;

        [TestMethod]
        [DataRow(Input1, 14)]
        [DataRow(Input2, 2)]
        [DataRow(Input3, 4)]
        public void It_locates_unique_antinodes(string input, int expected)
        {
            var res = Day08.LocateUniqueAntinodes(input);
            res.Should().Be(expected);
        }
        
        [TestMethod]
        [DataRow(Input4, 9)]
        [DataRow(Input1, 34)]
        public void It_locates_unique_antinodes_with_resonant_harmonics(string input, int expected)
        {
            var res = Day08.LocateUniqueAntinodesWithResonantHarmonics(input);
            res.Should().Be(expected);
        }
    }
}
